name: lint

on:
  push:
    branches: [ test-lint ]

jobs:
  lint-code:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pip install -r $GITHUB_WORKSPACE/2022-01-23-git-hooks/requirements.txt
    - name: Lint Code
      run: |
        cd $GITHUB_WORKSPACE/2022-01-23-git-hooks
        make check-format
        make lint